### ISSUE TITLE
sized_buffer_ptr

### ISSUE THREAD

**Issue by marehr** [noma/ham#10]
The SCIF backend of `buffer_ptr` has a `size` field.

https://github.com/noma/ham/blob/5649c04291336e0df172734ca8631d7be3020dbd/include/ham/net/communicator_scif.hpp#L34-L65

Is that the same size as the number of elements in that buffer?

I ask, because of the `sized_buffer_ptr` where size would be that.

**Comment by noma** [comment]
`registered size` as written in the comment means here the internally allocated size which has to be a multiple of the `PAGE_SIZE` for DMA reasons.

I could rename it to `registered_size` if that helps with your `sized_buffer_ptr`

**Comment by noma** [comment]
Fixed in b5d7ff149be9729b77d64f60acfcba0a9a2969e5.
