### ISSUE TITLE
CMake debug build in devel branch.

### ISSUE THREAD

**Issue by Phuzzyhead** [noma/ham#17]
I suggest adding 
```
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -DHAM_DEBUG_ON")
```
to ham/CMakeLists.txt so setting
```
-DCMAKE_BUILD_TYPE=Debug
```
will produce a debug build with all the HAM_DEBUG outputs enabled.

**Comment by noma** [comment]
Fixed in ddf9a27a54d21776d66ca15a7b6c989d1c33ab0a
